### ISSUE TITLE
Running tut.ABLflatTerrain.precursor arithmetic and running 2_solve reported an error

### ISSUE THREAD

**Issue by fengbao520** [NREL/SOWFA-6#64] opened 2023-09-11 07:38 UTC
Running tut.ABLflatTerrain.precursor arithmetic and running 2_solve reported an error.The terminal displays as shown

./2_solve: line 3: OpenFOAM-6-dev-central: command not found
Job killed (1)
./2_solve: line 15: scancel: command not found
Case not reconstructed and first time of boundaryData not fixed. Check if endTime dir exists.
ls: cannot access 'postProcessing/boundaryData/north': No such file or directory
ls: cannot access 'postProcessing/boundaryData/south': No such file or directory
ls: cannot access 'postProcessing/boundaryData/east': No such file or directory
ls: cannot access 'postProcessing/boundaryData/west': No such file or directory

The log. 2. decomposePar file displays as follows：
--> FOAM Warning :
From function void* Foam::dlOpen(const Foam::fileName&, bool)
in file POSIX.C at line 1234
dlopen error : libSOWFAincompressibleTurbulenceModels.so: cannot open shared object file: No such file or directory
--> FOAM Warning :
From function bool Foam::dlLibraryTable::open(const Foam::fileName&, bool)
in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 105
could not load "libSOWFAincompressibleTurbulenceModels.so"

I would greatly appreciate it if you could tell me where the mistake was or how to adjust it.
Thanks.

**Comment by rthedin** [comment] 2023-09-26 19:10
Duplicate of https://github.com/NREL/SOWFA-6/issues/63.
Unclear what your question is that hasn't been discussed in the issue above.

**Comment by fengbao520** [comment] 2023-09-27 08:44
> Duplicate of #63. Unclear what your question is that hasn't been discussed in the issue above.

Hello, I clarified that my problem is that after downloading sowfa-6-dev, it is not compiled in openfoam6, can you please give some suggestions for sowfa-6 compilation? Thank you very much and looking forward to your reply!

**Comment by fengbao8** [comment] 2023-11-27 07:14
> Duplicate of #63. Unclear what your question is that hasn't been discussed in the issue above.

Dear rethdin，I have errors in sowfa-6.Can you help me?

In sowfa-6 ABL precursor simulation is split into tut.ABLflatTerrain.precursor and tut.ABLflatTerrain.run. I have successfully run tut.ABLflatTerrain.precursor; but after running script 1_preprocess in tut.ABLflatTerrain.run two errors were reported . The errors are

--> FOAM FATAL IO ERROR:
keyword type is undefined in dictionary "/public21/home/sc94363/openfoam6/run/2/constant/ABLProperties.momentumSource"
file: /public21/home/sc94363/openfoam6/run/2/constant/ABLProperties.momentumSource
From function const Foam::entry &Foam::dictionary::lookupEntry(const Foam::word &, bool, bool) const
in file db/dictionary/dictionary.C at line 566.
FOAM exiting

And

FOAM FATAL ERROR:
Attempt to cast type patch to type lduInterface
From function To &Foam::refCast(From &) [with To = const Foam::lduInterface, From = const Foam::fvPatch]
in file /public1/soft/openfoam/OpenFOAM-6/src/OpenFOAM/lnInclude/typeInfo.H at line 114.
FOAM parallel run aborting

Error 1 is that I don't see the "given" function in tut.ABLflatTerrain.precursor, but it is required in tut.ABLflatTerrain.run. I'm not sure what I'm doing wrong there. Error 2 is in the log.1.renumberMesh file after tut.ABLflatTerrain.run is run.
I look forward to replies and hope to get help and answers.

**Comment by rthedin** [comment] 2023-11-27 19:06
The `momentumSource` and `temperatureSource` entries are related to the extra terms that go into the momentum and temperature equations. For the precursor, it controls the amount of background forcing needed to achieve your desired wind speed at your desired height. In that case, `computed` is given, meaning it will compute the driving forces based on other input parameters given within the subdictionary `momentumSource`. The computed forces are saved into `postProcessing`. For an inflow-outflow case (like the `tut.ABLflatTerrain.run` case), you need to use that information from the precursor, to ensure your simulation is consistent and your equations don't become unbalanced. In such case, you give type `given` and give a file containing the forcing to be added. What that means is that you need to use those forces from the precursor level. You can open the file from `postProcessing` and understand the data that is there. It needs to be re-formatted for to be used as input. The re-formatting is performed using an auxiliary processing script available at the companion `windtools` repository, [here](https://github.com/NREL/windtools/blob/main/bin/sowfa_convert_source_history.py). After you have the source quantities processed, the symlink from the precursor to the inflow-outflow case is done [here](https://github.com/NREL/SOWFA-6/blob/dev/exampleCases/tut.ABLflatTerrain.run/1_preprocess#L113).

Your second error is related to inconsistent cyclic and non-cyclic boundaries from your `blockMeshDict` and your initial condition/boundary conditions file.

**Comment by fengbao8** [comment] 2023-11-29 13:46
> Your second error is related to inconsistent cyclic and non-cyclic boundaries from your and your initial condition/boundary conditions file.`blockMeshDict`

Thanks for your advice, I have solved error 1. But error 2 I still don't know how to solve. I set the cyclic boundary condition and patch in blockMeshDict, but I still get the error.
Here are the settings in my blockMeshDict.
edges           
(
);

boundary
(
     lower
    {
        type patch;
        faces
        (
            (0 3 2 1)
        );
    }
    upper
    {
        type patch;
        faces
        (
            (4 5 6 7)
        );
    }
    west
    { 
        type cyclic;
        neighbourPatch east;
        faces
        (
            (0 4 7 3)
        );
    }
    east
    { 
        type cyclic;
        neighbourPatch west;
        faces
        (
            (1 2 6 5)
        );
    }
    north
    { 
        type cyclic;
        neighbourPatch south;
        faces
        (
            (3 7 6 2)
        );
    }
    south
    { 
        type cyclic;
        neighbourPatch north;
        faces
        (
            (0 1 5 4)
        );
    }
);

mergePatchPairs
(
);

**Comment by fengbao8** [comment] 2023-11-29 14:19
> Your second error is related to inconsistent cyclic and non-cyclic boundaries from your `blockMeshDict` and your initial condition/boundary conditions file.
Dear rethdin，
Thanks for your advice, I have solved error 1. But error 2 I still don't know how to solve. After I ran the tut.ABLflatTerrain.precursor example successfully, I changed the precursorDir in 1_preprocess in tut.ABLflatTerrain.run to the precursorDir of the tut.ABLflatTerrain.precursor that I ran successfully before. ABLflatTerrain.precursor.path and then run the script 1_preprocess and still get two errors.
One is the error that appears in the run log, as follows

--> FOAM FATAL ERROR: 

    request for surfaceScalarField UBlendingFactor from objectRegistry region0 failed
    available objects of type surfaceScalarField are

3
(
ghf
phi
buoyancyTerm
)
    From function const Type &Foam::objectRegistry::lookupObject(const Foam::word &) const [with Type = const Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh>]
    in file /public1/soft/openfoam/OpenFOAM-6/src/OpenFOAM/lnInclude/objectRegistryTemplates.C at line 193.

FOAM aborting
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const& Foam::objectRegistry::lookupObject<Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const>(Foam::word const&) const at ??:?
#3  Foam::localBlended<Foam::Vector<double> >::weights(Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&) const at ??:?
#4  Foam::fv::gaussConvectionScheme<Foam::Vector<double> >::fvmDiv(Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&) const at ??:?
#5  ? at ??:?
#6  ? at ??:?
#7  __libc_start_main in "/lib64/libc.so.6"
#8  ? at ??:?

The other error is still in log.1.renumberMesh as follows
--> FOAM FATAL ERROR: 
[42] Attempt to cast type patch to type lduInterface
[42] 
[42]     From function To &Foam::refCast(From &) [with To = const Foam::lduInterface, From = const Foam::fvPatch]
[42]     in file /public1/soft/openfoam/OpenFOAM-6/src/OpenFOAM/lnInclude/typeInfo.H at line 114.
[42] 
FOAM parallel run aborting
[42] 
[46] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[44] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[63] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[18] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[47] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[22] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[2] #0  Foam::error::printStack(Foam::Ostream&) at ??:?

If you have a good solution please let me know, I would appreciate it. Looking forward to your reply, thanks!

**Comment by fengbao8** [comment] 2023-11-29 14:21
> The `momentumSource` and `temperatureSource` entries are related to the extra terms that go into the momentum and temperature equations. For the precursor, it controls the amount of background forcing needed to achieve your desired wind speed at your desired height. In that case, `computed` is given, meaning it will compute the driving forces based on other input parameters given within the subdictionary `momentumSource`. The computed forces are saved into `postProcessing`. For an inflow-outflow case (like the `tut.ABLflatTerrain.run` case), you need to use that information from the precursor, to ensure your simulation is consistent and your equations don't become unbalanced. In such case, you give type `given` and give a file containing the forcing to be added. What that means is that you need to use those forces from the precursor level. You can open the file from `postProcessing` and understand the data that is there. It needs to be re-formatted for to be used as input. The re-formatting is performed using an auxiliary processing script available at the companion `windtools` repository, [here](https://github.com/NREL/windtools/blob/main/bin/sowfa_convert_source_history.py). After you have the source quantities processed, the symlink from the precursor to the inflow-outflow case is done [here](https://github.com/NREL/SOWFA-6/blob/dev/exampleCases/tut.ABLflatTerrain.run/1_preprocess#L113).
> 
> Your second error is related to inconsistent cyclic and non-cyclic boundaries from your `blockMeshDict` and your initial condition/boundary conditions file.

Dear rethdin，
Thanks for your advice, I have solved error 1. But error 2 I still don't know how to solve. After I ran the tut.ABLflatTerrain.precursor example successfully, I changed the precursorDir in 1_preprocess in tut.ABLflatTerrain.run to the precursorDir of the tut.ABLflatTerrain.precursor that I ran successfully before. ABLflatTerrain.precursor.path and then run the script 1_preprocess and still get two errors.
One is the error that appears in the run log, as follows

--> FOAM FATAL ERROR:

request for surfaceScalarField UBlendingFactor from objectRegistry region0 failed
available objects of type surfaceScalarField are
3
(
ghf
phi
buoyancyTerm
)
From function const Type &Foam::objectRegistry::lookupObject(const Foam::word &) const [with Type = const Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh>]
in file /public1/soft/openfoam/OpenFOAM-6/src/OpenFOAM/lnInclude/objectRegistryTemplates.C at line 193.

FOAM aborting
#0 Foam::error::printStack(Foam::Ostream&) at ??:?
https://github.com/NREL/SOWFA-6/pull/1 Foam::error::abort() at ??:?
https://github.com/NREL/SOWFA-6/pull/2 Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const& Foam::objectRegistry::lookupObject<Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const>(Foam::word const&) const at ??:?
https://github.com/NREL/SOWFA-6/issues/3 Foam::localBlended<Foam::Vector >::weights(Foam::GeometricField<Foam::Vector, Foam::fvPatchField, Foam::volMesh> const&) const at ??:?
https://github.com/NREL/SOWFA-6/pull/4 Foam::fv::gaussConvectionScheme<Foam::Vector >::fvmDiv(Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<Foam::Vector, Foam::fvPatchField, Foam::volMesh> const&) const at ??:?
https://github.com/NREL/SOWFA-6/issues/5 ? at ??:?
https://github.com/NREL/SOWFA-6/pull/6 ? at ??:?
https://github.com/NREL/SOWFA-6/issues/7 __libc_start_main in "/lib64/libc.so.6"
https://github.com/NREL/SOWFA-6/pull/8 ? at ??:?

The other error is still in log.1.renumberMesh as follows
--> FOAM FATAL ERROR:
[42] Attempt to cast type patch to type lduInterface
[42]
[42] From function To &Foam::refCast(From &) [with To = const Foam::lduInterface, From = const Foam::fvPatch]
[42] in file /public1/soft/openfoam/OpenFOAM-6/src/OpenFOAM/lnInclude/typeInfo.H at line 114.
[42]
FOAM parallel run aborting
[42]
[46] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[44] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[63] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[18] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[47] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[22] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[2] #0 Foam::error::printStack(Foam::Ostream&) at ??:?

If you have a good solution please let me know, I would appreciate it. Looking forward to your reply, thanks!

**Comment by rthedin** [comment] 2023-11-30 01:00
If you run the whole script blindly, you will not know where exactly it is failing. If the script isn't yet working as it should, you should not try to submit it as is. There are often lots of debugging to be done before one can submit a relatively complex script and know it's going to work given your environment, your compiled tools, and your setup.

With that said, the first error is clearly given:
```
request for surfaceScalarField UBlendingFactor from objectRegistry region0 failed
available objects of type surfaceScalarField are
3
(
ghf
phi
buoyancyTerm
)
```
What do you have in your UBlendingFactor table? It's not possible to tell where that error is coming from exactly since you are trying to execute a lot of things at once.

The second error is not SOWFA-related, as it is due to to renumberMesh. As mentioned, the error is related to mismatched patch types within your IC files and blockMeshDict.

**Comment by fengbao8** [comment] 2023-12-11 02:34
Dear rethdin,
Thank you for your reply.Your help has enabled me to solve some of these problems.But now I have a new problem.When I run the 1_preprocess.sh script in tut.ABLterrain I get the following error in the run log:

--> FOAM FATAL ERROR: 
Unknown LESModel type kEqnABL
Valid LESModel types:

10
(
DeardorffDiffStress
Smagorinsky
SpalartAllmarasDDES
SpalartAllmarasDES
SpalartAllmarasIDDES
WALE
dynamicKEqn
dynamicLagrangian
kEqn
kOmegaSSTDES
)
    From function static Foam::autoPtr<Foam::LESModel<BasicTurbulenceModel>> Foam::LESModel<BasicTurbulenceModel>::New(const BasicTurbulenceModel::alphaField &, const BasicTurbulenceModel::rhoField &, const Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> &, const Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> &, const Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> &, const BasicTurbulenceModel::transportModel &, const Foam::word &) [with BasicTurbulenceModel = Foam::IncompressibleTurbulenceModel<Foam::transportModel>]
    in file ../turbulenceModels/lnInclude/LESModel.C at line 161.
FOAM exiting

However, I found the kEqnABL.C & kEqnABL.H files in the sowfa file, compiled it again and ran it still with the above reported error.If you have any good suggestions please teach me and I look forward to hearing from you.

**Comment by rthedin** [comment] 2024-01-05 18:24
It seems like you have not compiled all the SOWFA libraries and utilities correctly-- see https://github.com/NREL/SOWFA-6/blob/dev/Allwmake#L9.

**Comment by fengbao8** [comment] 2024-01-06 08:18
> You don't seem to have compiled all the SOWFA libraries and utilities correctly - see https://github.com/NREL/SOWFA-6/blob/dev/Allwmake#L9.

Thank you for your reply! I'll go ahead and compile it again now.

**Comment by rthedin** [comment] 2024-02-26 19:23
Closing this. Feel free to re-open if if there are further questions.

**Closed by rthedin** 2024-02-26 19:23 UTC
